# Enable mouse mode
set -g mouse on

# Position status line at top of window
# set -g status-position top

# Enable 256 color support
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"

# Enable clipboard
set -g set-clipboard on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'nordtheme/tmux'

# Initialize TMUX plugin manager. (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
